name: Typescript NPM Quality

inputs:
  node-version:
    description: "Node.js version"
    default: "16.x"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
    - name: Install dependencies
      run: npm ci --ignore-scripts
      shell: bash
    - name: Compile Typescript
      run: npx tsc --noEmit
      shell: bash
    - name: Lint
      run: npm run lint --if-present
      shell: bash
