name: Java Quality

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
        cache: "maven"
    - name: Lint with Maven
      run: mvn git-code-format:validate-code-format -Dgcf.globPattern=**/*
      shell: bash
    - name: Test with Maven
      run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report -Dmaven.test.failure.ignore=false --batch-mode
      shell: bash
    - name: Upload code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: target/site/jacoco
