name: Java Quality

inputs:
  java-version:
    description: "Java version"
    default: "17"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}
        cache: "maven"
    - name: Lint with Maven
      run: mvn git-code-format:validate-code-format -Dgcf.globPattern=**/* --no-transfer-progress
      shell: bash
    - name: Test with Maven
      run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report -Dmaven.test.failure.ignore=false --batch-mode --no-transfer-progress
      shell: bash
    - name: Upload code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: target/site/jacoco
