name: Deploy
inputs:
  url:
    description: "Deploy url"
    required: true
  args:
    description: "Deploy arguments"
  confFile:
    description: "Configuration absolute path, if not provided searching for a docker-compose file"

runs:
  using: "composite"
  steps:
    - name: Build and deploy
      env:
        GITHUB_PROJECT: ${{github.repository}}
        BRANCH: ${{ github.ref_name }}
      run: curl -sG ${{ inputs.url }} -d project=$GITHUB_PROJECT -d branch=$BRANCH -d args=${{ inputs.args }} -d confFile=${{ inputs.confFile }}
      shell: bash
